### ISSUE TITLE
[Bug] Vanity slot does not work with accessories on Fabric 1.21

### ISSUE THREAD

**Issue by Hiusi** [wisp-forest/accessories#58] opened 2024-07-22 22:39 UTC
I'm trying to move to accessories from trinket, because I love how the ui is similar to curios, but when I tried to install 
Vanity mod which allow the player to hide armor
https://modrinth.com/mod/vanity
but I cannot seem to make it work, there is no new slot in my trinkets slot

**Comment by Dragon-Seeker** [comment] 2024-07-23 01:59
I do find it odd that such is not working but I do have a plan to add such kinda of idea native within Accessories as I already have a working prototype within the Experimental Screen rework. I will investigate why such dose not work though as it my be a problem with the trinkets layer

**Comment by Dragon-Seeker** [comment] 2024-07-26 20:13
![firefox_9jYupY7vK0](https://github.com/user-attachments/assets/c11f09d6-b804-4262-840f-c7f1d6fa416d)

Hmm, it seems to come down to issues with the slots having the same name overriding each other rather than loading different slots. I believe a fix can be done to fix this issue going forward.

**Comment by Dragon-Seeker** [comment] 2024-07-27 03:34
Was able to the find a solution and test such to be working with latest version of tclayer

**Comment by Hiusi** [comment] 2024-07-28 03:59
Hi! I just checked and update the mod but it seems like vanity slot is not there, am I doing something wrong?
Vanity version: 
TCLayer: 3.10.0 beta 3
Accessories: 1.0.0 beta 21

![image](https://github.com/user-attachments/assets/eb339b34-9d70-4b2b-ae34-b57518ab761f)

**Comment by Dragon-Seeker** [comment] 2024-07-28 04:19
![javaw_9C0tGENpTK](https://github.com/user-attachments/assets/130588cc-6017-4fa6-aac1-068fbf139d31)
Test pack with Vanity seems to be working so the full log and such is needed to better help

**Comment by Hiusi** [comment] 2024-07-28 04:31
this is my log! thank you ^^
[latest.log](https://github.com/user-attachments/files/16402217/latest.log)

**Comment by Dragon-Seeker** [comment] 2024-07-28 04:37
Honestly a quick glance at the log doesn't hint as much to the possible issue. Odd question but is it installed on the server as that is the only thing I can think that might be cause to why it don't appear

**Comment by Hiusi** [comment] 2024-07-28 05:10
I'm testing it on single player world, I will try it again after I come back home

**Comment by Dragon-Seeker** [comment] 2024-07-28 05:35
Ah, odd then. Maybe required to narrow down if another mod is causing the issue or if just vanity slots with accessories works on your end

**Comment by Hiusi** [comment] 2024-07-28 08:28
I just tested it with only vanity slot and accessories, but still have the same output
![image](https://github.com/user-attachments/assets/fee38cf0-9023-4798-9979-31d8bf7cdcfc)
![image](https://github.com/user-attachments/assets/1a97edf4-e31d-4986-af1d-0aadacf80a96)
[latest.log](https://github.com/user-attachments/files/16402652/latest.log)

**Comment by Hiusi** [comment] 2024-07-28 08:34
I tried to make a fresh start using curseforge instead of modrinth
![image](https://github.com/user-attachments/assets/7b2593cc-055b-47c7-b1cc-79d66551fb1a)
![image](https://github.com/user-attachments/assets/05e0d34d-5c9f-4f3b-a740-6b4335e92c52)
but still having the same output

**Comment by Dragon-Seeker** [comment] 2024-07-28 16:11
> I just tested it with only vanity slot and accessories, but still have the same output ![image](https://private-user-images.githubusercontent.com/152334258/352799108-fee38cf0-9023-4798-9979-31d8bf7cdcfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxODMzNzAsIm5iZiI6MTcyMjE4MzA3MCwicGF0aCI6Ii8xNTIzMzQyNTgvMzUyNzk5MTA4LWZlZTM4Y2YwLTkwMjMtNDc5OC05OTc5LTMxZDhiZjdjZGNmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxNjExMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzI2YmJlYjg3M2E0NWRiNTIzNzRjNDBkMGYyMmFhN2MxNDdkZDNiMjk5MDVjMzdlMTQ4NDI4ODM0MzlmMTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hCimWj34XOhjQoF4LphEFGRHNbjeYNuuHexiCdjeelw) ![image](https://private-user-images.githubusercontent.com/152334258/352799115-1a97edf4-e31d-4986-af1d-0aadacf80a96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxODMzNzAsIm5iZiI6MTcyMjE4MzA3MCwicGF0aCI6Ii8xNTIzMzQyNTgvMzUyNzk5MTE1LTFhOTdlZGY0LWUzMWQtNDk4Ni1hZjFkLTBhYWRhY2Y4MGE5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxNjExMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2UxZGY5ZTExZjM1ZWUzYmY2NGU3MDE3Mzc4N2FkNDViMTg0NTg0Y2E0ZGMxMTE0YTZiN2FmNGJhYjcxMjc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vn4cCFW_fh-5KVpfLhofCuxnDwdp9LSDe7bAwfDJqR0) 

Can you please try hitting the button on the right to show all slots as I believe such most likely is just hidden

**Comment by Dragon-Seeker** [comment] 2024-07-28 16:21
Hmmm wait also having a issue now... Wtf

**Comment by Dragon-Seeker** [comment] 2024-07-28 17:15
Testing in Dev seems to work. Odd the production build just doesn't even though it dose contain the fixes to make such work.

**Comment by Dragon-Seeker** [comment] 2024-07-28 17:20
Oddly a resource reload made them show up in production.

**Comment by Hiusi** [comment] 2024-07-28 17:21
omg thank you!, I thought that it's only me having the issue

> Hmmm wait also having a issue now... Wtf

**Comment by Dragon-Seeker** [comment] 2024-07-28 19:24
Found out its something to due with FAPI update that leads to this regression. Attempting to find a fix

**Comment by Dragon-Seeker** [comment] 2024-07-28 20:57
Ok, I pushed a fix and tested with the latest FAPI, and this is now fully working.

**Closed as completed by Dragon-Seeker** 2024-07-28 20:57 UTC
Labels: bug, Trinkets Compat
