### ISSUE TITLE
[1.21] `AttributeModifier` with the Same `ResourceLocation` are deduplicated even across `Attribute`s

### ISSUE THREAD

**Issue by lcy0x1** [wisp-forest/accessories#93] opened 2024-08-30 02:55 UTC
2 Bugs found for Accessories / CC layer:
1. Accessory with multiple attribute modifiers for different attributes using the same resource location will only have 1 displayed (probably due to `HashMap<ResourceLocation, ...>` somewhere)
1. `getAttributesTooltip` should receive the original attribute tooltips so that it can modify those generated with default rules. For example, change `+0.5` to `+50%`, change `+50%` to `x1.5`, or change tooltip colors. Currently it receives an empty input and only allows appending new lines

**Comment by lcy0x1** [comment] 2024-08-30 03:08
For problem 1, it's because `WrappedCurio::getDynamicModifiers` invokes `AccessoryAttributeBuilder::addExclusive`, which use `Map<ResourceLocation, AttributeModificationData>`. It should be using `Map<Holder<Attribute>, Map<ResourceLocation, AttributeModificationData>>` or `Table<Holder<Attribute>>, ResourceLocation, AttributeModificationData>` instead.

**Comment by Dragon-Seeker** [comment] 2024-08-30 18:35
1. Is the problem that `AttributeModifier` across **multiple** `Attribute` share the same `ResourceLocation` or is it the fact that multiple `AttributeModifier` have the same `ResourceLocation` for a **single** `Attribute`

**Comment by lcy0x1** [comment] 2024-08-31 01:09
@Dragon-Seeker The problem is having several `AttributeModifier`s sharing the same `ResourceLocation` for multiple `Attribute`s

The method provides a `ResourceLocation` that wants the accessory to use for its attribute modifiers. The issue 1 can technically be solved by appending a different suffix for every modifier, but most mods are not doing that

**Comment by Dragon-Seeker** [comment] 2024-08-31 21:19
Ah, that is really odd and frankly concerning as the `ResourceLocation` would be unique across all `AttributeModifier`'s but Minecraft doesn't enforce such even though they merged the id and name into one field to uniquely identifier the attribute with info about why or naming the modifier instance so it kind seems lazy to just share across every modifer but I guess since vanilla allows such I will need to adjust such even if I feel that this should not happen its just not enforced.

2. I did not know the API functioned like such as it is quite odd, to say the least. I understand its reasons but I believe that Accessories should attempt to use the Vanilla method `ItemStack.addModifierTooltip` and any mods should attempt injection within there to adjust the Attribute tooltips. Understandable that currently, this affects the Curios API but I don't really know exactly fix such an issue as the Accessories API isn't designed for such. Frankly, I don't want to redesign this as it seems like the incorrect method to deal with this.

**Comment by lcy0x1** [comment] 2024-09-01 02:18
The tooltip modification part is there to help with the missing Attribute tooltip customization from Forge/NeoForge. I think there is a PR regarding this in NeoForge currently?

**Comment by lcy0x1** [comment] 2024-09-01 02:22
If this PR is completed, I wouldn't need to use the odd attribute tooltip method
https://github.com/neoforged/NeoForge/pull/1371

**Comment by Dragon-Seeker** [comment] 2024-09-04 20:15
The accidental deduplication of modifiers has been fixed and the tooltip issue can be fixed by using mixin within Minecraft itemstack method to adjust the tooltip component yourself. Overall this issue is being closed as fixed as best can be.

**Closed as completed by Dragon-Seeker** 2024-09-04 20:15 UTC
Labels: bug

**Comment by Shibva** [comment] 2025-11-04 23:03
@Dragon-Seeker, sorry to neco-post on this, but I believe this same issue is plaguing the 1.20 version as well. The only explanation for this issue, in that some of my equipped stuff gets kicked off when I rejoin, is caused by the deduplication. Can a fix be applied here, too?

Oh, and I was not expecting @lcy0x1 to make a cameo here lmao.
