### ISSUE TITLE
Create Engineer Goggles doesnt show overlays when equipped as an Accessory

### ISSUE THREAD

**Issue by ToppyTopology** [wisp-forest/accessories#92] opened 2024-08-28 02:14 UTC
The Create engineer goggles when equipped should be able to show an overlay on certain blocks by the mod. The mod originally had curios support, though I assume it doesnt work here. The goggles work fine when equipped as a helmet slot.

**Comment by Dragon-Seeker** [comment] 2024-08-30 19:35
Are you using Curios Compat or Trinkets compat for this mod?

**Comment by ToppyTopology** [comment] 2024-08-31 14:51
> Are you using Curios Compat or Trinkets compat for this mod?

hello, Im using both compat mods

**Comment by Dragon-Seeker** [comment] 2024-08-31 20:41
What loader version is the Create Engineer Goggles using exactly? As if it was a Fabric version then it might be recommended to try updating the TCLayer as such may fix it.

**Comment by Dragon-Seeker** [comment] 2024-09-08 21:01
@ToppyTopology Any update as to whether this is still an issue?

**Comment by Dragon-Seeker** [comment] 2024-09-09 21:58
I am closing this as I can not reproduce such with the latest update, if it is still occurring comment / open an issue.

**Closed as completed by Dragon-Seeker** 2024-09-09 21:58 UTC

**Comment by DejaVuMan** [comment] 2024-09-16 02:08
I was able to reproduce this issue on my local instance 1.20.1 Forge version using:
* Beta 31 of Accessories
*  Compat Layer Beta 12 for

It seems to be **resolved** with:
* Beta 35 for Accessories 
* Beta 13 for Accessories

so if this issue ever comes up, comparing changes between these versions would be a good starting point.

Thanks!

Edit: It appears this issue does still occur in multiplayer.
