### ISSUE TITLE
Incompatibilities w/ spartan weaponry & simple hats

### ISSUE THREAD

**Issue by Stranding14** [wisp-forest/accessories#81] opened 2024-08-09 00:35 UTC
Noted the following mods have items that should work but do not
[spartan weaponry](https://www.curseforge.com/minecraft/mc-mods/spartan-weaponry): quiver is supposedly compatible with mods that add a dedicated quiver slot, but no luck.
[simple hats](https://www.curseforge.com/minecraft/mc-mods/simplehats) hats do not go in hat slot

**Comment by Stranding14** [comment] 2024-08-09 00:36
refs: 
running forge 47.3.1
accessories: 1.9.9-beta.26+1.20.1
accessories_cclayer-7.4.0-beta.8+1.20.1
accessories_tclater-3.8.1-beta.6+1.20.1

**Comment by Dragon-Seeker** [comment] 2024-08-09 00:46
Full log for such of the latest run would help

**Comment by Stranding14** [comment] 2024-08-09 00:51
here you go
[latest.log](https://github.com/user-attachments/files/16554513/latest.log)

**Comment by Dragon-Seeker** [comment] 2024-08-09 01:24
Also what mod is adding a Quiver slot as you state there is compat which seems to be present for Spartan Weaponry but any mod in particular, As by default it uses the back slot.

**Comment by Stranding14** [comment] 2024-08-09 01:28
Spartan weaponry doesn't add a quiver slot but states that if a mod adds a quiver slot, the quiver can be placed in it:
![image](https://github.com/user-attachments/assets/9fca3922-3fc5-4463-a718-1fef125bdf16)

**Comment by Dragon-Seeker** [comment] 2024-08-09 01:29
Ok, what mod are you using to add a quiver slot or are you adding a quiver slot?

**Comment by Stranding14** [comment] 2024-08-09 01:40
I believe supplementaries is adding the quiver slot, but it does not seem usable by anything else. 
![image](https://github.com/user-attachments/assets/4a0ada48-f69e-4d29-a0d4-a787cf4e31fb)

**Comment by Dragon-Seeker** [comment] 2024-08-09 01:45
Is such the fabric version of Supplementaries?

**Comment by Stranding14** [comment] 2024-08-09 01:46
It is the forge version - 2.8.17

**Comment by Dragon-Seeker** [comment] 2024-08-09 01:57
From looking thought the code base and adding such mod, the forge version uses the belt slot for quivers so some other mod is adding the quiver slot as the Fabric version is the one with the Quiver slot added.

**Comment by Dragon-Seeker** [comment] 2024-08-09 01:57
Also have no issue using Simple hats within production environment.

**Comment by Stranding14** [comment] 2024-08-09 01:58
hmm, I'll need to take a look then into my configs to see what's causing the incompatibilities & what's adding the quiver slot.

**Comment by Stranding14** [comment] 2024-08-09 02:11
Supplementaries was adding the quiver slot. After disabling the mod, it disappeared.

**Comment by Dragon-Seeker** [comment] 2024-08-09 02:25
Are you sure its not the fabric version of the mod? As such is the only one with dedicated slot for such built within the mod.

**Comment by Stranding14** [comment] 2024-08-09 02:27
I'll reinstall from curseforge to make sure

**Comment by Stranding14** [comment] 2024-08-09 02:33
it has been re-added after installing.

**Comment by Dragon-Seeker** [comment] 2024-08-09 02:45
Oh, Its because the mods trinkets files are in common that is also within the forge version of the mod lol. So the slot is a trinkets added slot being loaded by the TCLayer which means the id for the slot is not quivers as it must use the group info which is not so compatible with curios which is a problem I can't really fix.

**Comment by Dragon-Seeker** [comment] 2024-08-09 02:46
The code for the Supplementaries quiver for being within that slot is within the fabric version specifically meaning it will not work with anything. Kinda just a side effect of including all data files within common side.

**Comment by Stranding14** [comment] 2024-08-09 02:48
Ah so nothing can be done about that then. thanks for looking into it. I'll keep looking as to why the hats are not working with the correct slot.

**Comment by Dragon-Seeker** [comment] 2024-08-20 19:57
I am closing this issue and recommend if you are able to reproduce the issue with Simple hats that you make a new issue involving such

**Closed as completed by Dragon-Seeker** 2024-08-20 19:57 UTC
