### ISSUE TITLE
Accessories + Curios Compat Layer 1.20.1 crash with Embeddium Extra or Radium

### ISSUE THREAD

**Issue by Diamondback88** [wisp-forest/accessories#91] opened 2024-08-27 22:05 UTC
Accessories + Curios Compat Layer crashes when booted up either with the latest versions of Embeddium Extra or Radium.

NeoForge version 47.1.106 (1.20.1)

Mod List w/ Embeddium Extra:
accessories_cclayer-7.4.0-beta.11+1.20.1
accessories-neoforge-1.0.0-beta.28+1.20.1
cloth-config-11.1.118-forge
**embeddium-0.3.30+mc1.20.1
rubidium-extra-0.5.4.3+mc1.20.1-build.121**

Mod List w/ Radium:
accessories_cclayer-7.4.0-beta.11+1.20.1
accessories-neoforge-1.0.0-beta.28+1.20.1
cloth-config-11.1.118-forge
**radium-mc1.20.1-0.12.3+git.50c5c33**

[Embeddium Extra log](https://mclo.gs/2XEmeLH)
[Radium Log](https://mclo.gs/Fnebc1j)

**Comment by Dragon-Seeker** [comment] 2024-08-27 22:09
Duplicate of [67](https://github.com/wisp-forest/accessories/issues/67), the fix is to install Connector to have NanoLiveConfig have Fabric Loader class to stop the crash.

**Closed as completed by Dragon-Seeker** 2024-08-27 22:09 UTC
