### ISSUE TITLE
[Bug] [Forge 1.20.1] Multiplayer Syncing Problem on Player Join

### ISSUE THREAD

**Issue by maxim0p** [wisp-forest/accessories#42] opened 2024-07-02 10:37 UTC
When attempting to play Multiplayer/LAN with the accessories mod, only one player can access the accessory GUI at a time. The game will also crash when another player tries to access the accessory GUI screen. The crash is the same for both cases as it seems to be a client side crash.

**Crash log:** [https://pastebin.com/av3zfkq1](https://pastebin.com/av3zfkq1)

In the case of a multiplayer server, only the player who joined the server first can access the accessory GUI, anyone who joins after can press the inventory button, but nothing will happen. If the first player disconnects and reconnects the second player can now open the GUI, but when the first player presses the inventory button, they will crash, and subsequently anyone who joins after, can't open the GUI again. 
Also trying to use the "H" keybind to open the GUI does not work either and will also crash the game.

**Server video demonstration:** [https://streamable.com/njru9f](https://streamable.com/njru9f)

For LAN hosted single player world its pretty much the same but no crash since the host cant disconnect and reconnect. Only the LAN host can access the accessory GUI and not any other players.

**Singleplayer LAN video demonstration:** [https://streamable.com/l45uwa](https://streamable.com/l45uwa)

Note: I have connector present, and I'm using regular Forge, but I have done a lot of troubleshooting, with and without connector installed, using NeoForge, using different curios mods and trinkets mods. I also tested on a clean profile with just accessories and cloth config installed, and it all ends up in the same bug/crash.

Forge Version: _47.3.3_
Minecraft Version: _1.20.1_

Accessory mods used:
_accessories-1.0.0-alpha.24+1.20-neoforge_
_accessories_cclayer-7.4.0-alpha.13+1.20_
_accessories_tclayer-3.8.1-alpha.12+1.20_

**Comment by Dragon-Seeker** [comment] 2024-07-02 18:07
Wow this is a odd bug, will investigate such.

**Comment by Dragon-Seeker** [comment] 2024-07-02 18:57
Testing within the development for 1.21 without compat layers, I can't reproduce the issue. Will attempt such within 1.20.1 and then test with both compat layers.

**Comment by Dragon-Seeker** [comment] 2024-07-02 20:07
Seems to be involved with the `OnDatapackSyncEvent` on forge not firing leading to a problem where the client does not get the data required i.e. slot info and such. Meaning it's just a forge specific bug... argg

**Comment by Dragon-Seeker** [comment] 2024-07-02 20:56
Ok tracked it down to a bug within the code targeting the wrong entity when trying to reopen the screens for anyone who has AccessoriesScreen open when running `dataSync`

**Comment by Dragon-Seeker** [comment] 2024-07-02 21:00
~~Further checking on the CCLayer seems to still have the bug, most investigating!~~ Disregard such, building issues didn't make the latest changes.

**Comment by Dragon-Seeker** [comment] 2024-07-02 22:13
Pushed a fix for such to modrinth and curseforge

**Comment by maxim0p** [comment] 2024-07-02 23:15
Just tested the new version. The issue seems fixed from my testing. And the visual bug from #43 is fixed as well, the accessories now appear, and the game no longer crashes. Thank you!

I also tested the _keepInventory_ bug from #40 to see if it was related, and it still drops it seems. Interestingly though, that bug doesn't happen on the Alpha 23 version.

**Comment by Dragon-Seeker** [comment] 2024-07-03 00:24
Will look into the keep inventory bug coming up but closing this as fixed

**Closed as completed by Dragon-Seeker** 2024-07-03 00:24 UTC
Labels: bug
