### ISSUE TITLE
[Forge 1.20.1] Curios Attribute Modifiers not applying for non Curio implementing Items

### ISSUE THREAD

**Issue by MFRarDer** [wisp-forest/accessories#100] opened 2024-09-08 10:49 UTC
In original Curios Mod,I can use the command(For example:/give @p minecraft:apple{CurioAttributeModifiers:[{Slot:"ring", AttributeName:"generic.attack_damage", Name:"generic.attack_damage", Amount:20.0, Operation:0}]}).And The apple is not Curios originally.But I can make it to Ring driven by datapack.
But I use Accessories and Curios Compat Layer for Accessories ,this way is not work in this condition.If the item is driven by datapack,it is not work.And the item is create by other mod maker(For example:irons_spellbooks)I can use the command to adjust the attribute.(/give @p irons_spellbooks:mana_ring{CurioAttributeModifiers:[{Slot:"ring", AttributeName:"generic.attack_damage", Name:"generic.attack_damage", Amount:20.0, Operation:0}]})
![image](https://github.com/user-attachments/assets/a39545eb-0944-402d-83e4-2bb0cd8ed713)（I made item by KubeJS）
![image](https://github.com/user-attachments/assets/584fb87f-ca2c-4427-b449-d92b552a67ef)(It is not work!)
![image](https://github.com/user-attachments/assets/7a279af1-c32d-4493-9689-b2aa5c43ac88)(It made by Iron's Spellbook)
![image](https://github.com/user-attachments/assets/59ae074b-7b1f-4421-be2d-560562b1d839)(It is work)
Above Question,When I unloaded  Accessories and Curios Compat Layer for Accessories and loaded Curios API,This Nbt will work.
![image](https://github.com/user-attachments/assets/dff70d43-f3c4-48da-9f94-86febd6e2038)(Use Curios Api ,it is work)

**Comment by Dragon-Seeker** [comment] 2024-09-08 20:41
Ok so a bit confused about what the problem is here but I can assume that you are saying that the given attributes are not being found for the given item that is equipable within a given slot. I believe such comes down to the item not having a Curio within Curios API and I have a method to load the data-driven is being called for only curio item which is a oversight on my part

**Comment by Dragon-Seeker** [comment] 2024-09-09 22:00
Rework is for 1.21 fixing this issue but unknown if such will get backported to 1.20.1 as I have had very little time to keep backporting every fix to the previous version.

**Comment by MFRarDer** [comment] 2024-09-10 12:59
Thank You.If you still have the time, please optimize for version 1.20.1, as most mods are still on 1.20.1.

**Comment by Dragon-Seeker** [comment] 2024-09-13 01:18
Pushed a fix for 1.21 and for the foreseeable future I will only be updating such as I currently have limited time to backport bug fixes for 1.20.1 that are not critical issues. It may change coming up but as of now such is reality.

**Closed as completed by Dragon-Seeker** 2024-09-13 01:18 UTC
Labels: bug, Curios Compat
