### ISSUE TITLE
[Bug] 1.20.4 - Crash on launch with Trinkets Compatibility Layer

### ISSUE THREAD

**Issue by BlindTwig** [wisp-forest/accessories#21] opened 2024-05-28 16:14 UTC
Having the Trinkets Compatibility Layer installed at all, with or without mods that make use of the Trinkets API, causes a crash before reaching the main menu. Attached logs are from an instance with nothing but Accessories, the Compat. Layer, and their required mods.

[latest.log](https://github.com/wisp-forest/accessories/files/15472909/latest.log)
[crash-2024-05-28_12.12.30-client.txt](https://github.com/wisp-forest/accessories/files/15472913/crash-2024-05-28_12.12.30-client.txt)

**Comment by Dragon-Seeker** [comment] 2024-06-01 00:40
I believe this is caused by some recent changes involved with the Layer and Accessories. Such should be fixed with a upcoming update publishing later today

**Comment by Dragon-Seeker** [comment] 2024-06-01 01:40
The update has been released on modrinth.

**Comment by BlindTwig** [comment] 2024-06-01 01:47
Just tested and can confirm that it's fixed now. Thank you for the fast response!

**Closed as completed** 2024-06-01 02:10 UTC
Labels: bug
