### ISSUE TITLE
[1.21.1][Neoforge] Mod Fails to display Attribute layer on tooltip after item upgrade

### ISSUE THREAD

**Issue by ffuentesm** [wisp-forest/accessories#108] opened 2024-09-18 17:50 UTC
When using Accessories with the Curio layer, the mod fails to display the updated tooltip after the item is upgraded. 
The mod in the display is Iron'Spellbooks

The "Cooldown Reduction" line should have been added. 
The second image is from the same setting but using the Adorned mod instead of accessories

It looks like this:
![image](https://github.com/user-attachments/assets/852476a2-3ee3-4d0f-88be-d96123895443)

It should look like this: 
![image](https://github.com/user-attachments/assets/3223602d-f28d-4b08-8735-6eead23a287c)

**Comment by Dragon-Seeker** [comment] 2024-09-21 00:58
Can confirm such, seems to work with older version of accessories and compat layer so it seems like I updated something leading to this issue.

**Comment by ffuentesm** [comment] 2024-10-02 17:20
Any progress on this issue?

**Comment by Dragon-Seeker** [comment] 2024-10-02 18:47
Sadly no as I have tried to find the cause without success to why such is occuring

**Comment by ffuentesm** [comment] 2024-10-18 22:22
Just noticed now too, but it's also not displaying normal item descriptions. 
I mentioned this problem back in August on Discord, it was solved in Beta8 of CCL for 1.21. 
But the problem seems to be back in beta18.

Here is using Adorned
![image](https://github.com/user-attachments/assets/ae7d1eb6-c1ed-4732-b761-343e17889e53)
Here is using Accessories
![image](https://github.com/user-attachments/assets/6bc20bc3-aba4-4f62-bec0-b67052345592)

**Comment by Dragon-Seeker** [comment] 2024-10-19 03:54
So after some more searching I believe https://github.com/wisp-forest/accessories/commit/5ae8291565e0c24b096adfc4b85c2cea702ff817 and https://github.com/wisp-forest/accessories/commit/b6a3a650790fcc6adb2cad470ae99525d2b1ecfd should fix both problems. The tooltip problem came down to recent changes for the Curios API's that lead to it breaking again

**Comment by Dragon-Seeker** [comment] 2024-10-20 01:29
I am going to close this as I believe such to be fixed, open such again if found not to be

**Closed as completed by Dragon-Seeker** 2024-10-20 01:29 UTC
Labels: bug, unknown cause, Curios Compat
